package ru.stqa.pft.addreddbook.tests;// Generated by Selenium IDE

import org.hamcrest.CoreMatchers;
import org.hamcrest.MatcherAssert;
import org.junit.Assert;
import org.junit.Test;
import ru.stqa.pft.addreddbook.model.GroupData;
import ru.stqa.pft.addreddbook.model.Groups;

import java.util.List;
import java.util.Set;

import static org.hamcrest.MatcherAssert.assertThat;
import static org.junit.Assert.assertEquals;


public class DeleteGroupTest extends TestBase {

    @Test
    public void testDeleteGroup() {
        app.goTo().groupPage("GROUPS");
        if (app.group().list().size() == 0) {                     // этот цикл проверки предусловия, по наличию групп
            app.group().create(new GroupData().withName("test"));
        }
        Groups before = app.group().all();
        GroupData deletedGroup = before.iterator().next();
        app.group().delete(deletedGroup);
        Groups after = app.group().all();
        assertEquals(after.size(), before.size() - 1);
        assertThat(after, CoreMatchers.equalTo(before.without(deletedGroup) ));

    }


}
