package ru.stqa.pft.addreddbook.tests;// Generated by Selenium IDE

import org.junit.Test;
import ru.stqa.pft.addreddbook.model.GroupData;


public class DeleteGroupTest extends TestBase {

    @Test
    public void testDeleteGroup() {
        app.getNavigationHelper().gotoGroupPage("GROUPS");
        if (! app.getGroupHelper().isThereAGroup()){
            app.getGroupHelper().createGroup(new GroupData("test", null, null));
        }
        app.getGroupHelper().selectGroup("selected[]");
        app.getGroupHelper().deleteGroup("delete");
        app.getGroupHelper().returnToGroupPage("group page");

    }
}
