package ru.stqa.pft.addreddbook.tests;// Generated by Selenium IDE

import org.junit.Test;


public class DeleteGroupTest extends TestBase {
//коммент тест
    @Test
    public void testDeleteGroup() {
        app.getNavigationHelper().gotoGroupPage("GROUPS");
        app.getGroupHelper().selectGroup("selected[]");
        app.getGroupHelper().deleteGroup("delete");
        app.getGroupHelper().returnToGroupPage("group page");

    }
}
