package ru.stqa.pft.addreddbook.tests;// Generated by Selenium IDE


import org.junit.Assert;
import org.junit.Test;
import ru.stqa.pft.addreddbook.model.GroupData;

import java.util.List;


public class GroupCreationTest extends TestBase {

    @Test
    public void testGroupCreate() {
        app.getNavigationHelper().gotoGroupPage("GROUPS");
        // int before = app.getGroupHelper().getGroupCount(); - cчитает просто количество элементов групп
        List<GroupData> before = app.getContactHelper().getGroupList();  // считаем размер списка групп
        // app.getGroupHelper().createGroup(new GroupData ("zzz", null, null)); - один из вариантов создания группы, через отдельный метод
        app.getGroupHelper().initGroupCreation("new");
        app.getGroupHelper().fillGroupForm(new GroupData("test", "qwerty", "asd"));
        app.getGroupHelper().submitGroupCreation("submit");
        app.getGroupHelper().returnToGroupPage("group page");
        List<GroupData> after = app.getContactHelper().getGroupList();
        //int after = app.getGroupHelper().getGroupCount();
        Assert.assertEquals(after.size(),before.size() + 1);
        app.logout("LOGOUT");
    }

}
